name = "create-pack"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180594a94048e2dea95d709cc35e22a809f205aa8f130e6bc3f8b6038428e036"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
