name = "perfect-create"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "340ad9fea6746139fdc3a3c6d660a9bc5e60aebbfc315010e244fd1e30be4135"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
