name = "create-pack"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df4af701a3fc20a125ba56df28399402e96ed528150febff6d80955654b150ee"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
