name = "create-pack"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "651018ba2013569ad41bf4ae7c8d79dbc59786a40c62608d3fb15464aa375d0d"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
