name = "perfect-create"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0a389ed924380b6ea8723777e7a2c2ca792825b93c29299f51de30403db0ace"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
