name = "perfect-create"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d9ca45ed77e728e41ef425f1d6929f6906cab0de074b73f8f1b63050532226d"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
