name = "perfect-create"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55cc1858d72d82583f6cffadd683c1c4c9f155a9ded6c8e2c53c4f6483d77e77"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
