name = "perfect-create"
author = "Julia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "374cccf8624d02cf3e1e04258f625fce1f292c255240fa1e207d44c951a52902"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
