name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: workflow/nix-shell-action@v3
        with:
          packages: packwiz 
          script: |
            packwiz modrinth export -o modpack-${{ github.ref_name }}.mrpack
            packwiz curseforge export -o modpack-${{ github.ref_name }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            modpack-${{ github.ref_name }}.mrpack
            modpack-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
